### ISSUE TITLE
Still works?

### ISSUE THREAD

**Issue by SamueldaCostaAraujoNunes** [arnellebalane/google-meet-pip#10]
I tried to use the extension for the first time, downloading from Google Extensions, I couldn't use the extension!

**Comment by arnellebalane** [comment]
Hi @SamueldaCostaAraujoNunes , yes the extension still works!

The issue you encountered usually happens when you are already in a Google Meet meeting when you installed the extension. Did you try refreshing the Google Meet page after you installed the extension?

**Comment by SamueldaCostaAraujoNunes** [comment]
Já sim, no dia não. Mas no dia seguinte, o PIP funcionou!
