### ISSUE TITLE
Google Meet PIP doesn't work.

### ISSUE THREAD

**Issue by Dr-Sauce** [arnellebalane/google-meet-pip#11]
I've tried it on Chrome and Brave. But it doesn't work at all.

![20210507_111821](https://user-images.githubusercontent.com/82555878/117389544-7cf5c900-af27-11eb-99c4-bf5ee80bb577.png)

![image](https://user-images.githubusercontent.com/82555878/117388501-d5c46200-af25-11eb-993f-7701c1399776.png)

**Comment by arnellebalane** [comment]
Possible reasons for this that I can think of:
- All meeting participants didn't have their video turned on
- Can't check for now, but Brave might not have support for Picture-in-Picture API yet which is what this extension relies on.

Closing this for now, feel free to reopen if you still encounter the same issue after checking the above. Thanks!
