### ISSUE TITLE
Doesn't work anymore after 1.1.1 release

### ISSUE THREAD

**Issue by jaklan** [arnellebalane/google-meet-pip#19]
Hi, when clicking "Show" button from the pop-up - the PiP window appears for less than second in the bottom right corner, then disappears and no more happens, so the extension at the moment is unfortunately unusable 😕

**Comment by arnellebalane** [comment]
Hi @jaklan , thank you for reporting this. I'll have to take a look. The popup on the page is meant to be a temporary solution while I work on a proper way to initiate PiP windows. Basically I will move the list of users from the extension popup UI directly into the Google Meet page itself, since opening a PiP window now requires a user gesture.

So sorry for this inconvenience. This behavior you encountered when clicking on "Show" was not something I found while testing this temporary solution. When you get the chance to try it again, can you help me check in your DevTools console if there are any errors logged? Thank you very much!

**Comment by jaklan** [comment]
@arnellebalane maybe I'm doing sth wrong, but I have opened that view:
![image](https://user-images.githubusercontent.com/24907857/151154190-f92e9257-d5c6-4dd3-a812-0aefde7bce9f.png)
also turned on "Collect errors", but when I interact with the extension during the meeting - I see no logged interactions.

**Comment by arnellebalane** [comment]
@jaklan In the DevTools console in the Google Meet page while you're on a call, do you see any errors related to PiP in there?

**Comment by jaklan** [comment]
@arnellebalane no error, only this:
![image](https://user-images.githubusercontent.com/24907857/151155950-882ff205-e350-4072-9828-6dff5de0ef64.png)
and when I hover over it - the "end call" button is highlighted.

**Comment by jaklan** [comment]
I guess there's sth wrong here, because reading the code:
```javascript
function enableHangupControl() {
  var control = getHangupControl();
  console.log(control);
  navigator.mediaSession.setActionHandler('hangup', function () {
    exitPictureInPicture();
    control.click();
    setTimeout(function () {
      var hangup = getHangupDialogControl();
      hangup.click();
    }, 500);
  });
  return function () {
    navigator.mediaSession.setActionHandler('hangup', null);
  };
}
```
I should get some "hangup control", but it seems the only thing I get is `exitPictureInPicture();`.

**Comment by jaklan** [comment]
And if you find it helpful - that's my setup of icons in GMeet (maybe it's different in corporate GMeet or sth):
![image](https://user-images.githubusercontent.com/24907857/151156564-d606e1fc-c314-4007-93b4-e0ab36899479.png)

**Comment by arnellebalane** [comment]
Hi @jaklan , and when you saw the button logged in the DevTools console, you still have the PiP window appear for a while and disappear right away?

**Comment by jaklan** [comment]
@arnellebalane right, this log message and the quick "blink" of the PiP window happen almost at the same moment.

**Comment by arnellebalane** [comment]
@jaklan Thanks for taking your time to check 🙏

**Comment by arnellebalane** [comment]
Hi @jaklan , `v1.2.0` of the extension is now published (#20). Hopefully it resolves your issue. Thank you! 🙇

**Comment by jaklan** [comment]
@arnellebalane seems to work! 🎉

**Comment by jaklan** [comment]
@arnellebalane today I tested it during the actual meeting with other participants - and unfortunately nothing changed, it still doesn't work - `the PiP window appears for less than second in the bottom right corner, then disappears and no more happens`. The difference is this time I don't get any logs from the extension.

**Comment by jaklan** [comment]
@arnellebalane can I help with the debugging in any way? I'm really missing the working extension, I used to use it on a daily basis 😕
