### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by igoracmelo** [arnellebalane/google-meet-pip#25]
I was using it almost everyday and suddenly it stopped working.
Current version: 1.2.0
![image](https://user-images.githubusercontent.com/85039990/168447049-c072224c-a095-4eca-8d41-f3a3b1b119b8.png)

**Comment by igoracmelo** [comment]
Investigating here I found out that the extension is failing to detect names.
Probably because Meet changed something.

![image](https://user-images.githubusercontent.com/85039990/168484708-c01c3a11-2372-494e-9ca3-b4a8e42b17bd.png)

**Comment by igoracmelo** [comment]
I managed to fix it. Making a PR...

**Comment by deepakpunjabi** [comment]
Hey, I built this version but it is still not working on Chrome 102.0.5005.61 on macOS. Could you suggest any debugging steps?
<img width="305" alt="image" src="https://user-images.githubusercontent.com/17640076/170669967-36f17789-70c2-4deb-adb4-4ff97ec9ea76.png">
