### ISSUE TITLE
PIP implentation

### ISSUE THREAD

**Issue by dmuralimohan** [arnellebalane/google-meet-pip#31]
how implement pip like google meet based with exciting features?

**Comment by arnellebalane** [comment]
You can use the Picture-in-Picture API to implement PiP-based experiences in your Web applications, here are some references:
- https://developer.mozilla.org/en-US/docs/Web/API/Picture-in-Picture_API
- https://medium.com/arnelle-balane/the-picture-in-picture-api-30415372009f
